import { Product } from "./types";

export const products: Product[] = [
  {
    id: "1",
    name: "Laptop Pro",
    description: "High performance laptop for programming and gaming.",
    price: 1200,
    category: "electronics",
    imageUrl: "https://picsum.photos/id/180/400/300",
  },
  {
    id: "2",
    name: "Wireless Mouse",
    description: "Comfortable wireless mouse.",
    price: 35,
    category: "electronics",
    imageUrl: "https://picsum.photos/id/1060/400/300",
  },
  {
    id: "3",
    name: "Mechanical Keyboard",
    description: "RGB mechanical keyboard.",
    price: 90,
    category: "electronics",
    imageUrl: "https://picsum.photos/id/48/400/300",
  },
  {
    id: "4",
    name: "27 Inch Monitor",
    description: "Full HD IPS display.",
    price: 280,
    category: "electronics",
    imageUrl: "https://picsum.photos/id/1/400/300",
  },
  {
    id: "5",
    name: "Bluetooth Speaker",
    description: "Portable speaker with deep bass.",
    price: 70,
    category: "electronics",
    imageUrl: "https://picsum.photos/id/250/400/300",
  },

  {
    id: "6",
    name: "Programming Book",
    description: "Master modern web development.",
    price: 40,
    category: "books",
    imageUrl: "https://picsum.photos/id/20/400/300",
  },
  {
    id: "7",
    name: "React Handbook",
    description: "Complete React Guide.",
    price: 45,
    category: "books",
    imageUrl: "https://picsum.photos/id/24/400/300",
  },
  {
    id: "8",
    name: "Next.js Guide",
    description: "Learn Next.js from scratch.",
    price: 50,
    category: "books",
    imageUrl: "https://picsum.photos/id/25/400/300",
  },
  {
    id: "9",
    name: "Clean Code",
    description: "Improve coding practices.",
    price: 60,
    category: "books",
    imageUrl: "https://picsum.photos/id/26/400/300",
  },
  {
    id: "10",
    name: "Algorithms Book",
    description: "DSA concepts explained.",
    price: 55,
    category: "books",
    imageUrl: "https://picsum.photos/id/27/400/300",
  },

  {
    id: "11",
    name: "Cotton T-Shirt",
    description: "Comfortable cotton t-shirt.",
    price: 20,
    category: "clothing",
    imageUrl: "https://picsum.photos/id/1005/400/300",
  },
  {
    id: "12",
    name: "Blue Jeans",
    description: "Slim fit denim jeans.",
    price: 45,
    category: "clothing",
    imageUrl: "https://picsum.photos/id/1011/400/300",
  },
  {
    id: "13",
    name: "Hoodie",
    description: "Winter fleece hoodie.",
    price: 60,
    category: "clothing",
    imageUrl: "https://picsum.photos/id/1012/400/300",
  },
  {
    id: "14",
    name: "Running Shoes",
    description: "Lightweight sports shoes.",
    price: 90,
    category: "clothing",
    imageUrl: "https://picsum.photos/id/21/400/300",
  },
  {
    id: "15",
    name: "Jacket",
    description: "Stylish waterproof jacket.",
    price: 120,
    category: "clothing",
    imageUrl: "https://picsum.photos/id/1001/400/300",
  },
  {
    id: "16",
    name: "Office Chair",
    description: "Ergonomic office chair.",
    price: 180,
    category: "furniture",
    imageUrl: "https://picsum.photos/id/29/400/300",
  },
  {
    id: "17",
    name: "Wooden Table",
    description: "Premium wooden study table.",
    price: 320,
    category: "furniture",
    imageUrl: "https://picsum.photos/id/30/400/300",
  },
  {
    id: "18",
    name: "Bookshelf",
    description: "Modern wooden bookshelf.",
    price: 210,
    category: "furniture",
    imageUrl: "https://picsum.photos/id/42/400/300",
  },
  {
    id: "19",
    name: "Bedside Lamp",
    description: "LED bedside lamp.",
    price: 40,
    category: "furniture",
    imageUrl: "https://picsum.photos/id/96/400/300",
  },
  {
    id: "20",
    name: "Coffee Table",
    description: "Minimal wooden coffee table.",
    price: 140,
    category: "furniture",
    imageUrl: "https://picsum.photos/id/175/400/300",
  },
  {
    id: "21",
    name: "Gaming Headset",
    description: "Noise cancelling headset.",
    price: 110,
    category: "electronics",
    imageUrl: "https://picsum.photos/id/3/400/300",
  },
  {
    id: "22",
    name: "Smart Watch",
    description: "Fitness tracking smartwatch.",
    price: 230,
    category: "electronics",
    imageUrl: "https://picsum.photos/id/201/400/300",
  },
  {
    id: "23",
    name: "USB Hub",
    description: "4 Port USB Hub.",
    price: 25,
    category: "electronics",
    imageUrl: "https://picsum.photos/id/180/400/300",
  },
  {
    id: "24",
    name: "JavaScript Guide",
    description: "Master JavaScript.",
    price: 48,
    category: "books",
    imageUrl: "https://picsum.photos/id/28/400/300",
  },
  {
    id: "25",
    name: "TypeScript Handbook",
    description: "Learn TypeScript.",
    price: 52,
    category: "books",
    imageUrl: "https://picsum.photos/id/31/400/300",
  },
  {
    id: "26",
    name: "Polo T-Shirt",
    description: "Premium polo t-shirt.",
    price: 35,
    category: "clothing",
    imageUrl: "https://picsum.photos/id/1004/400/300",
  },
  {
    id: "27",
    name: "Sneakers",
    description: "Casual sneakers.",
    price: 95,
    category: "clothing",
    imageUrl: "https://picsum.photos/id/1018/400/300",
  },
  {
    id: "28",
    name: "Cap",
    description: "Adjustable sports cap.",
    price: 15,
    category: "clothing",
    imageUrl: "https://picsum.photos/id/1027/400/300",
  },
  {
    id: "29",
    name: "Travel Bag",
    description: "Large travel backpack.",
    price: 70,
    category: "clothing",
    imageUrl: "https://picsum.photos/id/1040/400/300",
  },
  {
    id: "30",
    name: "Winter Sweater",
    description: "Warm wool sweater.",
    price: 80,
    category: "clothing",
    imageUrl: "https://picsum.photos/id/1050/400/300",
  },
];
