import { Product } from "./types";

export const products: Product[] = [
  {
    id: "1",
    name: "Laptop Pro",
    description: "High performance laptop for programming and gaming.",
    price: 1200,
    category: "electronics",
    imageUrl: "https://picsum.photos/id/180/400/300",
  },
  {
    id: "2",
    name: "Wireless Mouse",
    description: "Comfortable wireless mouse.",
    price: 35,
    category: "electronics",
    imageUrl: "https://picsum.photos/id/1060/400/300",
  },
  {
    id: "3",
    name: "Mechanical Keyboard",
    description: "RGB mechanical keyboard.",
    price: 90,
    category: "electronics",
    imageUrl: "https://picsum.photos/id/48/400/300",
  },
  {
    id: "4",
    name: "27 Inch Monitor",
    description: "Full HD IPS display.",
    price: 280,
    category: "electronics",
    imageUrl: "https://picsum.photos/id/1/400/300",
  },
  {
    id: "5",
    name: "Bluetooth Speaker",
    description: "Portable speaker with deep bass.",
    price: 70,
    category: "electronics",
    imageUrl: "https://picsum.photos/id/250/400/300",
  },

  {
    id: "6",
    name: "Programming Book",
    description: "Master modern web development.",
    price: 40,
    category: "books",
    imageUrl: "https://picsum.photos/id/20/400/300",
  },
  {
    id: "7",
    name: "React Handbook",
    description: "Complete React Guide.",
    price: 45,
    category: "books",
    imageUrl: "https://picsum.photos/id/24/400/300",
  },
  {
    id: "8",
    name: "Next.js Guide",
    description: "Learn Next.js from scratch.",
    price: 50,
    category: "books",
    imageUrl: "https://picsum.photos/id/25/400/300",
  },
  {
    id: "9",
    name: "Clean Code",
    description: "Improve coding practices.",
    price: 60,
    category: "books",
    imageUrl: "https://picsum.photos/id/26/400/300",
  },
  {
    id: "10",
    name: "Algorithms Book",
    description: "DSA concepts explained.",
    price: 55,
    category: "books",
    imageUrl: "https://picsum.photos/id/27/400/300",
  },

  {
    id: "11",
    name: "Cotton T-Shirt",
    description: "Comfortable cotton t-shirt.",
    price: 20,
    category: "clothing",
    imageUrl: "https://picsum.photos/id/1005/400/300",
  },
  {
    id: "12",
    name: "Blue Jeans",
    description: "Slim fit denim jeans.",
    price: 45,
    category: "clothing",
    imageUrl: "https://picsum.photos/id/1011/400/300",
  },
  {
    id: "13",
    name: "Hoodie",
    description: "Winter fleece hoodie.",
    price: 60,
    category: "clothing",
    imageUrl: "https://picsum.photos/id/1012/400/300",
  },
  {
    id: "14",
    name: "Running Shoes",
    description: "Lightweight sports shoes.",
    price: 90,
    category: "clothing",
    imageUrl: "https://picsum.photos/id/21/400/300",
  },
  {
    id: "15",
    name: "Jacket",
    description: "Stylish waterproof jacket.",
    price: 120,
    category: "clothing",
    imageUrl: "https://picsum.photos/id/1001/400/300",
  },
];